### ISSUE TITLE
a few questions

### ISSUE THREAD

**Issue by jjk3** [scrapy/slybot#68]
is there a slybot discussion or mailing list?

1. where does slybot save the extracted data? is it possible to force it to store on mongodb or redis? 

2. how can I make slybot look for text of element (a[contains('text')]) instead of the link url?

3. How does slybot figure out which page it's on?

4. how do you make slybot input a keyword in a search box (is it able to find this automatically?) given a list of keywords, and then go into search results, go to next page, and scrape stuff?

**Comment by pablohoffman** [comment]
Slybot has been replaced by Portia, please user Porita's mailing list for support questions:
https://groups.google.com/forum/#!forum/portia-scraper
