### ISSUE TITLE
Slybot is not in Pypi yet

### ISSUE THREAD

**Issue by WoLpH** [scrapy/slybot#78]
Not sure if it ever was or if the docs are simply incorrect but `pip install slybot` does nothing.

Understandably given that `slybot` isn't anywhere in the Pypi index: https://pypi.python.org/pypi?%3Aaction=search&term=slybot&submit=search

**Comment by pablohoffman** [comment]
Portia has replaced slybot and will be available on pypi after its first release. The installation instructions are here: https://github.com/scrapinghub/portia#running-portia-locally
